version: "3.9"
services:
  grafana:
    image: grafana/grafana:9.2.0
    ports:
      - "3000:3000"
    container_name: grafana-9.2.0
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:14
    # image: netscoutngeniuspulse/sp-api-reporting-postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  python:
    image: netscoutngeniuspulse/sp-api-reporting-python:latest
    container_name: python-3.10
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - postgres