version: "3.9"
services:
  grafana:
    image: grafana/grafana:9.2.0
    ports:
      - "3000:3000"
    container_name: grafana-9.2.0
    volumes: 
      - ${PWD}/grafana/provisioning/postgres.yaml:/etc/grafana/provisioning/datasources/postgres.yaml
      - ${PWD}/grafana/provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ${PWD}/grafana/dashboards/Sightline.json:/var/lib/grafana/dashboards/Sightline.json
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  python:
    image: netscoutngeniuspulse/sp-api-reporting-python:latest
    container_name: python-3.10
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - postgres