version: "3.9"
services:
  grafana:
    image: grafana/grafana:9.2.0
    ports:
      - "3000:3000"
    volumes: 
      - ${PWD}/grafana/provisioning/postgres.yaml:/etc/grafana/provisioning/datasources/postgres.yaml
      - ${PWD}/grafana/provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ${PWD}/grafana/dashboards/Sightline.json:/var/lib/grafana/dashboards/Sightline.json
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  sp-ingest:
    image: python:3.10-alpine
    volumes: 
      - ${PWD}/sp-ingest/requirements.txt:/requirements.txt
      - ${PWD}/sp-ingest/src:/src
    command: sh -c  "pip install -r requirements.txt && python3 src/python_middleware.py --setup SETUP"
    environment:
      - SL_LEADER
      - SL_APITOKEN
      - SL_INITIAL_ALERT_DAYS=${SL_INITIAL_ALERT_DAYS:-30}
      - SL_UPDATE_ALERT_DAYS=${SL_UPDATE_ALERT_DAYS:-1}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    depends_on:
      - postgres
