version: "3.9"
services:
  grafana:
    image: grafana/grafana:9.2.0
    ports:
      - "3000:3000"
    container_name: grafana-9.2.0
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  python:
    image: python:3.10-bullseye
    container_name: python-3.10
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes: 
      - /etc/resolv.conf:/etc/resolv.conf
    depends_on:
      - postgres
    
