version: "3.9"
services:
  grafana:
    image: grafana/grafana:9.2.0
    ports:
      - "3000:3000"
    volumes: 
      - ${PWD}/grafana/provisioning/postgres.yaml:/etc/grafana/provisioning/datasources/postgres.yaml
      - ${PWD}/grafana/provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ${PWD}/grafana/dashboards/Sightline.json:/var/lib/grafana/dashboards/Sightline.json
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  sp-ingest:
    image: python:3.10-alpine
    volumes: 
      - ${PWD}/sp-ingest/requirements.txt:/requirements.txt
      - ${PWD}/sp-ingest/src:/src
    command: sh -c  "pip install -r requirements.txt && python3 src/python_middleware.py --setup SETUP"
    env_file:
      - .env
    depends_on:
      - postgres