{
 "title": "Sightline: Alert EVENT - Statistics (v2.927)",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Severity_Level",
    "query": "select importance_txt from v_security_levels__of_alerts"
   },
   {
    "name": "Alert_Type",
    "query": "select alert_type_txt from v_alert_types__of_alerts"
   },
   {
    "name": "Managed_Object",
    "query": "select managed_object_name from v_managed_object_names__of_alerts"
   },
   {
    "name": "Managed_Object_exclude",
    "label": "Managed Object (exclude)",
    "query": "select ''\nunion all\nselect managed_object_name from v_managed_object_names__of_alerts;"
   },
   {
    "name": "Direction",
    "query": "select direction from v_directions__of_alerts"
   },
   { "name": "min_impact_gbps", "label": "Impact (Gbps) >=", "query": "0" },
   {
    "name": "Mitigation_Type",
    "query": "select mitigation_subtypes from v_mitigation_subtypes__of_alerts;"
   },
   { "name": "Mitigated", "query": "True,False" },
   { "name": "Automitigation", "query": "True,False" },
   { "name": "AggregationPeriod", "label": "... per X (=Day/Week/Month)", "query": "Day,Week,Month" },
   {
    "name": "p_offset_selected_duration",
    "label": "\"Previous\" offset = selected duration",
    "query": "True,False"
   },
   {
    "name": "p_offset_days",
    "label": "\"Previous\" offset - Days ",
    "query": "0"
   },
   {
    "name": "p_offset_months",
    "label": "\"Previous\" offset - Months ",
    "query": "0"
   },
   {
    "name": "p_offset_weeks",
    "label": "\"Previous\" offset - Weeks ",
    "query": "0"
   },
   {
    "name": "p_offset_years",
    "label": "\"Previous\" offset - Years",
    "query": "0"
   },
   {
    "name": "Timezone",
    "query": "select name from pg_timezone_names order by name;"
   },
   { "name": "Database", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Database last time updated:",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  alert__last_update AS \"time\"\nFROM v_operational_info\n\n"
    }
   ]
  },
  {
   "title": "Query Time Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH vars AS(\nSELECT\n(\n/* var: v_offset */\n(CASE WHEN ($p_offset_selected_duration=true)\n  THEN ($__timeTo()::timestamptz - $__timeFrom()::timestamptz)::interval\n  ELSE interval '0'\n  END)\n  + make_interval(years => $p_offset_years, months => $p_offset_months, weeks => $p_offset_weeks, days => $p_offset_days)) as v_offset\n\n)\n\nSELECT 'Selected' As \"Query Periods\", (($__timeFrom())::timestamptz) as \"TIME-FROM\", (($__timeTo())::timestamptz) as \"TIME-TO\"\n\nunion all\n\nSELECT 'Previous' As \"Query Periods\",(($__timeFrom())::timestamptz - v_offset) as \"TIME-FROM\", (($__timeTo())::timestamptz - v_offset) \"TIME-TO\"\nFrom vars"
    }
   ]
  },
  {
   "title": "Alerts (attack focus)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  id AS \"Alert ID\", managed_object_name AS \"Managed Object\", host_address AS \"IP Address\", array_to_string(misuse_types || protocols, ',') AS \"Vectors\", importance_txt AS \"Severity\", direction AS \"Direction\", start_time as \"time\", EXTRACT(epoch FROM duration::interval) as \"Duration\", alert_type_txt AS \"Alert Type\", \n  impact_bps AS \"bps\", impact_pps AS \"pps\", INITCAP(mitigated::text) as \"Mitigated\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time) and impact_bps > 0 and impact_pps > 0\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nORDER BY \"bps\" desc\n"
    }
   ]
  },
  {
   "title": "Maximum Alert Traffic Rate [F01]",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  max(impact_bps) AS \"bps\",\n  max(impact_pps) AS \"pps\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n"
    }
   ]
  },
  {
   "title": "TREND: Maximum Alert Traffic Rate  [F03]",
   "type": "stat",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH vars AS(\nSELECT\n(\n/* var: v_offset */\n(CASE WHEN ($p_offset_selected_duration=true)\n  THEN ($__timeTo()::timestamptz - $__timeFrom()::timestamptz)::interval\n  ELSE interval '0'\n  END)\n  + make_interval(years => $p_offset_years, months => $p_offset_months, weeks => $p_offset_weeks, days => $p_offset_days)) as v_offset\n\n),\nSET1 as (\nSELECT\n  max(impact_bps) AS \"bps\",\n  max(impact_pps) AS \"pps\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  \n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n),\nSET2 as (\nSELECT\n  max(impact_bps) AS \"bps_prev\",\n  max(impact_pps) AS \"pps_prev\"\nFROM v_alert, vars\nWHERE\n  start_time BETWEEN $__timeFrom()::timestamptz - v_offset\n  AND\n  $__timeTo()::timestamptz - v_offset\n  \n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n)\n\nselect \"bps\", \"pps\", COALESCE(((\"bps\"/NULLIF(\"bps_prev\",0))*100), 0) as \"bps%\", COALESCE(((\"pps\"/NULLIF(\"pps_prev\",0))*100), 0) as \"pps%\",\"bps_prev\", \"pps_prev\" from set1, set2\n\n"
    }
   ]
  },
  {
   "title": "Maximum Alert Traffic Rate  (bps) / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  max(impact_bps) AS \"bps\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Maximum Alert Traffic Rate  (pps) / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  max(impact_pps) AS \"pps\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Alert Traffic Rate  (bps) (cumulative) / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  sum(impact_bps) AS \"bps\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Alert Traffic Rate  (pps) (cumulative) / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  sum(impact_pps) AS \"pps\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TREND: Average Alert Traffic Rate [F03]",
   "type": "stat",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH vars AS(\nSELECT\n(\n/* var: v_offset */\n(CASE WHEN ($p_offset_selected_duration=true)\n  THEN ($__timeTo()::timestamptz - $__timeFrom()::timestamptz)::interval\n  ELSE interval '0'\n  END)\n  + make_interval(years => $p_offset_years, months => $p_offset_months, weeks => $p_offset_weeks, days => $p_offset_days)) as v_offset\n\n),\nSET1 as (\nSELECT\n  avg(impact_bps) AS \"bps\",\n  avg(impact_pps) AS \"pps\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  \n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n),\nSET2 as (\nSELECT\n  avg(impact_bps) AS \"bps_prev\",\n  avg(impact_pps) AS \"pps_prev\"\nFROM v_alert,vars\nWHERE\n  start_time BETWEEN $__timeFrom()::timestamptz - v_offset\n  AND\n  $__timeTo()::timestamptz - v_offset\n  \n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n)\n\nselect \"bps\", \"pps\", COALESCE(((\"bps\"/NULLIF(\"bps_prev\",0))*100), 0) as \"bps%\", COALESCE(((\"pps\"/NULLIF(\"pps_prev\",0))*100), 0) as \"pps%\", \"bps_prev\", \"pps_prev\" from set1, set2\n"
    }
   ]
  },
  {
   "title": "TREND: Alert Count per Severity Level [F03]",
   "type": "stat",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 114 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH vars AS(\nSELECT\n(\n/* var: v_offset */\n(CASE WHEN ($p_offset_selected_duration=true)\n  THEN ($__timeTo()::timestamptz - $__timeFrom()::timestamptz)::interval\n  ELSE interval '0'\n  END)\n  + make_interval(years => $p_offset_years, months => $p_offset_months, weeks => $p_offset_weeks, days => $p_offset_days)) as v_offset\n\n),\nalert_count AS (\nSELECT\n  count(importance_txt = 'Low' OR NULL) AS \"Low\",\n  count(importance_txt = 'Medium' OR NULL) AS \"Medium\",\n  count(importance_txt = 'High' OR NULL) AS \"High\",\n  count(id) as \"Total\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n),\nalert_count_prev AS (\nSELECT\n  count(importance_txt = 'Low' OR NULL) AS \"Low_prev\",\n  count(importance_txt = 'Medium' OR NULL) AS \"Medium_prev\",\n  count(importance_txt = 'High' OR NULL) AS \"High_prev\",\n  count(id) as \"Total_prev\"\nFROM v_alert,vars\nWHERE\n  start_time BETWEEN $__timeFrom()::timestamptz - v_offset\n  AND\n  $__timeTo()::timestamptz - v_offset\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n)\n\nselect \"High\", \"Medium\", \"Low\", \"Total\", COALESCE(((\"High\"::float/NULLIF(\"High_prev\",0))*100), 0)::int as \"high%\", COALESCE(((\"Medium\"::float/NULLIF(\"Medium_prev\",0))*100), 0)::int as \"medium%\", COALESCE(((\"Low\"::float/NULLIF(\"Low_prev\",0))*100), 0)::int as \"low%\", COALESCE(((\"Total\"::float/NULLIF(\"Total_prev\",0))*100), 0)::int as \"total%\", \"High_prev\", \"Medium_prev\", \"Low_prev\", \"Total_prev\" from alert_count, alert_count_prev"
    }
   ]
  },
  {
   "title": "Alert Count by Severity Level / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  count(importance_txt = 'Low' OR NULL) AS \"Low\",\n  count(importance_txt = 'Medium' OR NULL) AS \"Medium\",\n  count(importance_txt = 'High' OR NULL) AS \"High\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Attack Type Count  [F01]",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 140 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH SET1 as (\nSELECT\n  unnest(misuse_types || protocols) AS \"AttackVector\" FROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n)\n\nSELECT \"AttackVector\", count(\"AttackVector\") from SET1\nGroup by 1\norder by 2 desc\n"
    }
   ]
  },
  {
   "title": "Attack Type Count (High only) [F01]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 154 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH SET1 as (\nSELECT\n  unnest(misuse_types || protocols) AS \"AttackVector\" FROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  importance_txt = 'High'\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n)\n\nSELECT \"AttackVector\", count(\"AttackVector\") from SET1\nGroup by 1\norder by 2 desc\n"
    }
   ]
  },
  {
   "title": "Attack Type Count / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH SET1 as (\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  unnest(misuse_types || protocols) AS \"AttackVector\" \nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n)\nSELECT \"time\", \"AttackVector\" , count(\"AttackVector\") As \"Count:  \" from SET1\nGroup by 1,2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Alert Type Count / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  count(alert_type_txt = 'Profiled Network' OR NULL) AS \"Profile Network\",\n  count(alert_type_txt = 'Profiled Router' OR NULL) AS \"Profile Router\",\n  count(alert_type_txt = 'Host Detection' OR NULL) AS \"Host Detection\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "TREND: Max Alert Duration per Security Level [F03]",
   "type": "stat",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH vars AS(\nSELECT\n(\n/* var: v_offset */\n(CASE WHEN ($p_offset_selected_duration=true)\n  THEN ($__timeTo()::timestamptz - $__timeFrom()::timestamptz)::interval\n  ELSE interval '0'\n  END)\n  + make_interval(years => $p_offset_years, months => $p_offset_months, weeks => $p_offset_weeks, days => $p_offset_days)) as v_offset\n\n),\nalert_count AS (\nSELECT\n  EXTRACT(epoch FROM max(duration) FILTER (WHERE importance_txt = 'Low' OR NULL)) AS \"Low\",\n  EXTRACT(epoch FROM max(duration) FILTER (WHERE importance_txt = 'Medium' OR NULL)) AS \"Medium\",\n  EXTRACT(epoch FROM max(duration) FILTER (WHERE importance_txt = 'High' OR NULL)) AS \"High\",\n  EXTRACT(epoch FROM max(duration)) as \"Any\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n),\nalert_count_prev AS (\nSELECT\n  EXTRACT(epoch FROM max(duration) FILTER (WHERE importance_txt = 'Low' OR NULL)) AS \"Low_prev\",\n  EXTRACT(epoch FROM max(duration) FILTER (WHERE importance_txt = 'Medium' OR NULL)) AS \"Medium_prev\",\n  EXTRACT(epoch FROM max(duration) FILTER (WHERE importance_txt = 'High' OR NULL)) AS \"High_prev\",\n  EXTRACT(epoch FROM max(duration)) as \"Any_prev\"\nFROM v_alert,vars\nWHERE\n  start_time BETWEEN $__timeFrom()::timestamptz - v_offset\n  AND\n  $__timeTo()::timestamptz - v_offset\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n)\n\nselect \"High\", \"Medium\", \"Low\", \"Any\", COALESCE(((\"High\"::float/NULLIF(\"High_prev\",0))*100), 0)::int as \"high%\", COALESCE(((\"Medium\"::float/NULLIF(\"Medium_prev\",0))*100), 0)::int as \"medium%\", COALESCE(((\"Low\"::float/NULLIF(\"Low_prev\",0))*100), 0)::int as \"low%\", COALESCE(((\"Any\"::float/NULLIF(\"Any_prev\",0))*100), 0)::int as \"any%\", \"High_prev\", \"Medium_prev\", \"Low_prev\", \"Any_prev\" from alert_count, alert_count_prev"
    }
   ]
  },
  {
   "title": "Max Alert Duration / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  EXTRACT(epoch FROM max(duration) FILTER (WHERE importance_txt = 'Low' OR NULL)) AS \"Low\",\n  EXTRACT(epoch FROM max(duration) FILTER (WHERE importance_txt = 'Medium' OR NULL)) AS \"Medium\",\n  EXTRACT(epoch FROM max(duration) FILTER (WHERE importance_txt = 'High' OR NULL)) AS \"High\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Alert Duration (cumulative) / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  EXTRACT(epoch FROM sum(duration) FILTER (WHERE importance_txt = 'Low' OR NULL)) AS \"Low\",\n  EXTRACT(epoch FROM sum(duration) FILTER (WHERE importance_txt = 'Medium' OR NULL)) AS \"Medium\",\n  EXTRACT(epoch FROM sum(duration) FILTER (WHERE importance_txt = 'High' OR NULL)) AS \"High\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TREND: Average Alert Duration per Security Level [F03]",
   "type": "stat",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 236 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH vars AS(\nSELECT\n(\n/* var: v_offset */\n(CASE WHEN ($p_offset_selected_duration=true)\n  THEN ($__timeTo()::timestamptz - $__timeFrom()::timestamptz)::interval\n  ELSE interval '0'\n  END)\n  + make_interval(years => $p_offset_years, months => $p_offset_months, weeks => $p_offset_weeks, days => $p_offset_days)) as v_offset\n\n),\nalert_count AS (\nSELECT\n  EXTRACT(epoch FROM avg(duration) FILTER (WHERE importance_txt = 'Low' OR NULL)) AS \"Low\",\n  EXTRACT(epoch FROM avg(duration) FILTER (WHERE importance_txt = 'Medium' OR NULL)) AS \"Medium\",\n  EXTRACT(epoch FROM avg(duration) FILTER (WHERE importance_txt = 'High' OR NULL)) AS \"High\",\n  EXTRACT(epoch FROM avg(duration)) as \"Any\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n),\nalert_count_prev AS (\nSELECT\n  EXTRACT(epoch FROM avg(duration) FILTER (WHERE importance_txt = 'Low' OR NULL)) AS \"Low_prev\",\n  EXTRACT(epoch FROM avg(duration) FILTER (WHERE importance_txt = 'Medium' OR NULL)) AS \"Medium_prev\",\n  EXTRACT(epoch FROM avg(duration) FILTER (WHERE importance_txt = 'High' OR NULL)) AS \"High_prev\",\n  EXTRACT(epoch FROM avg(duration)) as \"Any_prev\"\nFROM v_alert,vars\nWHERE\n  start_time BETWEEN $__timeFrom()::timestamptz - v_offset\n  AND\n  $__timeTo()::timestamptz - v_offset\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n)\n\nselect \"High\", \"Medium\", \"Low\", \"Any\", COALESCE(((\"High\"::float/NULLIF(\"High_prev\",0))*100), 0)::int as \"high%\", COALESCE(((\"Medium\"::float/NULLIF(\"Medium_prev\",0))*100), 0)::int as \"medium%\", COALESCE(((\"Low\"::float/NULLIF(\"Low_prev\",0))*100), 0)::int as \"low%\", COALESCE(((\"Any\"::float/NULLIF(\"Any_prev\",0))*100), 0)::int as \"any%\", \"High_prev\", \"Medium_prev\", \"Low_prev\", \"Any_prev\" from alert_count, alert_count_prev"
    }
   ]
  },
  {
   "title": "Average Alert Duration / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 258 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  EXTRACT(epoch FROM avg(duration) FILTER (WHERE importance_txt = 'Low' OR NULL)) AS \"Low\",\n  EXTRACT(epoch FROM avg(duration) FILTER (WHERE importance_txt = 'Medium' OR NULL)) AS \"Medium\",\n  EXTRACT(epoch FROM avg(duration) FILTER (WHERE importance_txt = 'High' OR NULL)) AS \"High\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Alerts (mitigation focus)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 268 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  id AS \"Alert ID\", managed_object_name AS \"Managed Object\", importance_txt AS \"Severity\", start_time as \"time\", \n  impact_bps AS \"bps\", impact_pps AS \"pps\", INITCAP(mitigated::text) as \"Mitigated\", array_to_string(mitigation_types, ',') as \"MitigationTypes\", INITCAP(automitigation::text) AS \"Automitigation\",\n  r_drop_bps_max_tms_and_flowspec_and_blackhole as \"ANY bps max drop\",  r_drop_pps_max_tms_and_flowspec_and_blackhole as \"ANY pps max drop\",\n  r_drop_bytes_tms_and_flowspec_and_blackhole as \"ANY bytes drop\",  r_drop_packets_tms_and_flowspec_and_blackhole as \"ANY packets drop\",\n\n  r_drop_bps_max_tms as \"TMS bps max drop\",  r_drop_pps_max_tms as \"TMS pps max drop\",\n  r_drop_bytes_tms as \"TMS bytes drop\",  r_drop_packets_tms as \"TMS packets drop\",\n\n  r_drop_bps_max_flowspec as \"FS bps max drop\",  r_drop_pps_max_flowspec as \"FS pps max drop\",\n  r_drop_bytes_flowspec as \"FS bytes drop\",  r_drop_packets_flowspec as \"FS packets drop\",\n  \n  r_drop_bps_max_blackhole as \"BH bps max drop\",  r_drop_pps_max_blackhole as \"BH pps max drop\",\n  r_drop_bytes_blackhole as \"BH bytes drop\",  r_drop_packets_blackhole as \"BH packets drop\"\n\nFROM v_alert\nWHERE\n  $__timeFilter(start_time) and impact_bps > 0 and impact_pps > 0\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nORDER BY \"bps\" desc\n"
    }
   ]
  },
  {
   "title": "Mitigated Alerts Count vs. High Alerts Count[F01]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 281 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  count(mitigated OR NULL) AS \"Mitigated Alerts\",\n  count(importance_txt = 'High' OR NULL) AS \"High Alerts\",\n  count(importance_txt) AS \"ALL Alerts\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n"
    }
   ]
  },
  {
   "title": "Mitigated Alerts Count / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 288 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  count(mitigated OR NULL) AS \"Mitigated Alerts\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Alert Mitigation Count by MitigationType Combination",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 299 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH SET1 as (\nSELECT id, unnest(mitigation_types) as unnested_mitigation_types\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n  \nORDER BY 1 ASC, 2 DESC\n),\n\nSET2 AS (\nSELECT id, string_agg(unnested_mitigation_types, ' | ') as mitigation_type_combinations\nFROM SET1\nWHERE\n NOT unnested_mitigation_types = 'None'\nGROUP BY 1\n),\nSET3 as (\nSELECT  mitigation_type_combinations as \"Mitigation Type Combination\", count(mitigation_type_combinations) as \"Count\"\nFROM SET2\nGROUP BY 1\nORDER BY 2 DESC\n)\n\nSELECT *\nFROM SET3\n\nUNION ALL\n\nSELECT 'ANY', sum(\"Count\")\nFROM SET3\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Alert MitigationType Count [F01]",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 307 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  count('TMS' = ANY(mitigation_types) OR NULL) AS \"TMS\",\n  count('FlowSpec' = ANY(mitigation_types) OR NULL) AS \"FlowSpec\",\n  count('Blackhole' = ANY(mitigation_types) OR NULL) AS \"Blackhole\",\n  sum(array_length(NULLIF(mitigation_types, ARRAY['None']),1)) AS \"SUM\" FROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n"
    }
   ]
  },
  {
   "title": "Alert MitigationType Count  / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 314 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  count('Blackhole' = ANY(mitigation_types) OR NULL) AS \"Blackhole\",\n  count('FlowSpec' = ANY(mitigation_types) OR NULL) AS \"FlowSpec\",\n  count('TMS' = ANY(mitigation_types) OR NULL) AS \"TMS\"\n  \nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Maximum Alert Mitigation Traffic Drop Rate by MitigationType [F01]",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 325 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  max(r_drop_bps_max_tms_and_flowspec_and_blackhole) AS \"ANY bps\",\n  max(r_drop_pps_max_tms_and_flowspec_and_blackhole) AS \"ANY pps\",\n  max(r_drop_bps_max_tms) AS \"TMS bps\",\n  max(r_drop_pps_max_tms) AS \"TMS pps\",\n  max(r_drop_bps_max_flowspec) AS \"Flowspec bps\",\n  max(r_drop_pps_max_flowspec) AS \"Flowspec pps\",\n  max(r_drop_bps_max_blackhole) AS \"Blackhole bps\",\n  max(r_drop_pps_max_blackhole) AS \"Blackhole pps\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n"
    }
   ]
  },
  {
   "title": "TREND: Max Alert Mitigation Traffic Drop Rate by MitigationType  [F03]",
   "type": "stat",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 341 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH vars AS(\nSELECT\n(\n/* var: v_offset */\n(CASE WHEN ($p_offset_selected_duration=true)\n  THEN ($__timeTo()::timestamptz - $__timeFrom()::timestamptz)::interval\n  ELSE interval '0'\n  END)\n  + make_interval(years => $p_offset_years, months => $p_offset_months, weeks => $p_offset_weeks, days => $p_offset_days)) as v_offset\n\n),\nSET1 AS (\nSELECT\n  max(r_drop_bps_max_tms_and_flowspec_and_blackhole) AS \"ANY bps\",\n  max(r_drop_pps_max_tms_and_flowspec_and_blackhole) AS \"ANY pps\",\n  max(r_drop_bps_max_tms) AS \"TMS bps\",\n  max(r_drop_pps_max_tms) AS \"TMS pps\",\n  max(r_drop_bps_max_flowspec) AS \"Flowspec bps\",\n  max(r_drop_pps_max_flowspec) AS \"Flowspec pps\",\n  max(r_drop_bps_max_blackhole) AS \"Blackhole bps\",\n  max(r_drop_pps_max_blackhole) AS \"Blackhole pps\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n),\nSET2 AS (\nSELECT\n  max(r_drop_bps_max_tms_and_flowspec_and_blackhole) AS \"ANY bps (prev)\",\n  max(r_drop_pps_max_tms_and_flowspec_and_blackhole) AS \"ANY pps (prev)\",\n  max(r_drop_bps_max_tms) AS \"TMS bps (prev)\",\n  max(r_drop_pps_max_tms) AS \"TMS pps (prev)\",\n  max(r_drop_bps_max_flowspec) AS \"Flowspec bps (prev)\",\n  max(r_drop_pps_max_flowspec) AS \"Flowspec pps (prev)\",\n  max(r_drop_bps_max_blackhole) AS \"Blackhole bps (prev)\",\n  max(r_drop_pps_max_blackhole) AS \"Blackhole pps (prev)\"\nFROM v_alert, vars\nWHERE\n  start_time BETWEEN $__timeFrom()::timestamptz - v_offset\n  AND\n  $__timeTo()::timestamptz - v_offset\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n)\n\nSELECT \"ANY bps\", \"ANY pps\", \"TMS bps\", \"TMS pps\", \"Flowspec bps\", \"Flowspec pps\", \"Blackhole bps\", \"Blackhole pps\",\nCOALESCE(((\"ANY bps\"::float/NULLIF(\"ANY bps (prev)\",0))*100), 0)::int as \"ANY bps %\",\nCOALESCE(((\"ANY pps\"::float/NULLIF(\"ANY pps (prev)\",0))*100), 0)::int as \"ANY pps %\",\n\nCOALESCE(((\"TMS bps\"::float/NULLIF(\"TMS bps (prev)\",0))*100), 0)::int as \"TMS bps %\",\nCOALESCE(((\"TMS pps\"::float/NULLIF(\"TMS pps (prev)\",0))*100), 0)::int as \"TMS pps %\",\n\nCOALESCE(((\"Flowspec bps\"::float/NULLIF(\"Flowspec bps (prev)\",0))*100), 0)::int as \"Flowspec bps %\",\nCOALESCE(((\"Flowspec pps\"::float/NULLIF(\"Flowspec pps (prev)\",0))*100), 0)::int as \"Flowspec pps %\",\n\nCOALESCE(((\"Blackhole bps\"::float/NULLIF(\"Blackhole bps (prev)\",0))*100), 0)::int as \"Blackhole bps %\",\nCOALESCE(((\"Blackhole pps\"::float/NULLIF(\"Blackhole pps (prev)\",0))*100), 0)::int as \"Blackhole pps %\",\n\n\"ANY bps (prev)\", \"ANY pps (prev)\", \"TMS bps (prev)\", \"TMS pps (prev)\", \"Flowspec bps (prev)\", \"Flowspec pps (prev)\", \"Blackhole bps (prev)\", \"Blackhole pps (prev)\"\nfrom SET1, SET2"
    }
   ]
  },
  {
   "title": "Maximum Alert Mitigation Traffic Drop Rate by MitigationType (bps) / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 360 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  max(r_drop_bps_max_tms_and_flowspec_and_blackhole) AS \"ANY bps\",\n  max(r_drop_bps_max_tms) AS \"TMS bps\",\n  max(r_drop_bps_max_flowspec) AS \"Flowspec bps\",\n  max(r_drop_bps_max_blackhole) AS \"Blackhole bps\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Maximum Alert Mitigation Traffic Drop Rate by MitigationType (pps) / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 371 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  max(r_drop_pps_max_tms_and_flowspec_and_blackhole) AS \"ANY pps\",\n  max(r_drop_pps_max_tms) AS \"TMS pps\",\n  max(r_drop_pps_max_flowspec) AS \"Flowspec pps\",\n  max(r_drop_pps_max_blackhole) AS \"Blackhole pps\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Alert Mitigation Traffic Drop Rate by MitigationType (bps) (cumulative) / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 382 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  sum(r_drop_bps_max_tms_and_flowspec_and_blackhole) AS \"ANY bps\",\n  sum(r_drop_bps_max_tms) AS \"TMS bps\",\n  sum(r_drop_bps_max_flowspec) AS \"Flowspec bps\",\n  sum(r_drop_bps_max_blackhole) AS \"Blackhole bps\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Alert Mitigation Traffic Drop Rate by MitigationType (pps) (cumulative) / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 393 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  sum(r_drop_pps_max_tms_and_flowspec_and_blackhole) AS \"ANY pps\",\n  sum(r_drop_pps_max_tms) AS \"TMS pps\",\n  sum(r_drop_pps_max_flowspec) AS \"Flowspec pps\",\n  sum(r_drop_pps_max_blackhole) AS \"Blackhole pps\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Alert Mitigation Dropped Traffic by MitigationType [F01]",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 404 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  sum(r_drop_bytes_tms_and_flowspec_and_blackhole) AS \"ANY Bytes\",\n  sum(r_drop_packets_tms_and_flowspec_and_blackhole) AS \"ANY Packets\",\n  sum(r_drop_bytes_tms) AS \"TMS Bytes\",\n  sum(r_drop_packets_tms) AS \"TMS Packets\",\n  sum(r_drop_bytes_flowspec) AS \"Flowspec Bytes\",\n  sum(r_drop_packets_flowspec) AS \"Flowspec Packets\",\n  sum(r_drop_bytes_blackhole) AS \"Blackhole Bytes\",\n  sum(r_drop_packets_blackhole) AS \"Blackhole Packets\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n"
    }
   ]
  },
  {
   "title": "TREND: Alert Mitigation Dropped Traffic by MitigationType [F03]",
   "type": "stat",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 418 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH vars AS(\nSELECT\n(\n/* var: v_offset */\n(CASE WHEN ($p_offset_selected_duration=true)\n  THEN ($__timeTo()::timestamptz - $__timeFrom()::timestamptz)::interval\n  ELSE interval '0'\n  END)\n  + make_interval(years => $p_offset_years, months => $p_offset_months, weeks => $p_offset_weeks, days => $p_offset_days)) as v_offset\n\n),\nSET1 AS (\nSELECT\n  sum(r_drop_bytes_tms_and_flowspec_and_blackhole) AS \"ANY Bytes\",\n  sum(r_drop_packets_tms_and_flowspec_and_blackhole) AS \"ANY Packets\",\n  sum(r_drop_bytes_tms) AS \"TMS Bytes\",\n  sum(r_drop_packets_tms) AS \"TMS Packets\",\n  sum(r_drop_bytes_flowspec) AS \"Flowspec Bytes\",\n  sum(r_drop_packets_flowspec) AS \"Flowspec Packets\",\n  sum(r_drop_bytes_blackhole) AS \"Blackhole Bytes\",\n  sum(r_drop_packets_blackhole) AS \"Blackhole Packets\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n),\nSET2 AS (\nSELECT\n  sum(r_drop_bytes_tms_and_flowspec_and_blackhole) AS \"ANY Bytes (prev)\",\n  sum(r_drop_packets_tms_and_flowspec_and_blackhole) AS \"ANY Packets (prev)\",\n  sum(r_drop_bytes_tms) AS \"TMS Bytes (prev)\",\n  sum(r_drop_packets_tms) AS \"TMS Packets (prev)\",\n  sum(r_drop_bytes_flowspec) AS \"Flowspec Bytes (prev)\",\n  sum(r_drop_packets_flowspec) AS \"Flowspec Packets (prev)\",\n  sum(r_drop_bytes_blackhole) AS \"Blackhole Bytes (prev)\",\n  sum(r_drop_packets_blackhole) AS \"Blackhole Packets (prev)\"\nFROM v_alert, vars\nWHERE\n  start_time BETWEEN $__timeFrom()::timestamptz - v_offset\n  AND\n  $__timeTo()::timestamptz - v_offset\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n)\n\nSELECT \"ANY Bytes\", \"ANY Packets\", \"TMS Bytes\", \"TMS Packets\", \"Flowspec Bytes\", \"Flowspec Packets\", \"Blackhole Bytes\", \"Blackhole Packets\",\nCOALESCE(((\"ANY Bytes\"::float/NULLIF(\"ANY Bytes (prev)\",0))*100), 0)::int as \"ANY Bytes %\",\nCOALESCE(((\"ANY Packets\"::float/NULLIF(\"ANY Packets (prev)\",0))*100), 0)::int as \"ANY Packets %\",\n\nCOALESCE(((\"TMS Bytes\"::float/NULLIF(\"TMS Bytes (prev)\",0))*100), 0)::int as \"TMS Bytes %\",\nCOALESCE(((\"TMS Packets\"::float/NULLIF(\"TMS Packets (prev)\",0))*100), 0)::int as \"TMS Packets %\",\n\nCOALESCE(((\"Flowspec Bytes\"::float/NULLIF(\"Flowspec Bytes (prev)\",0))*100), 0)::int as \"Flowspec Bytes %\",\nCOALESCE(((\"Flowspec Packets\"::float/NULLIF(\"Flowspec Packets (prev)\",0))*100), 0)::int as \"Flowspec Packets %\",\n\nCOALESCE(((\"Blackhole Bytes\"::float/NULLIF(\"Blackhole Bytes (prev)\",0))*100), 0)::int as \"Blackhole Bytes %\",\nCOALESCE(((\"Blackhole Packets\"::float/NULLIF(\"Blackhole Packets (prev)\",0))*100), 0)::int as \"Blackhole Packets %\",\n\n\"ANY Bytes (prev)\", \"ANY Packets (prev)\", \"TMS Bytes (prev)\", \"TMS Packets (prev)\", \"Flowspec Bytes (prev)\", \"Flowspec Packets (prev)\", \"Blackhole Bytes (prev)\", \"Blackhole Packets (prev)\"\nfrom SET1, SET2"
    }
   ]
  },
  {
   "title": "Alert Mitigation Dropped Traffic by MitigationType (bytes) / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 435 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  sum(r_drop_bytes_tms_and_flowspec_and_blackhole) AS \"ANY Bytes\",\n  sum(r_drop_bytes_tms) AS \"TMS Bytes\",\n  sum(r_drop_bytes_flowspec) AS \"Flowspec Bytes\",\n  sum(r_drop_bytes_blackhole) AS \"Blackhole Bytes\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Alert Mitigation Dropped Traffic by MitigationType (packets) / $AggregationPeriod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 446 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  date_trunc('$AggregationPeriod', start_time AT TIME ZONE ('$Timezone')::text)::timestamptz AS \"time\",\n  sum(r_drop_packets_tms_and_flowspec_and_blackhole) AS \"ANY Packets\",\n  sum(r_drop_packets_tms) AS \"TMS Packets\",\n  sum(r_drop_packets_flowspec) AS \"Flowspec Packets\",\n  sum(r_drop_packets_blackhole) AS \"Blackhole Packets\"\n\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Top Managed Objects by Alert Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 457 },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  managed_object_name AS \"Managed Object\", count(id) AS \"Count\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 2 desc\n"
    }
   ]
  },
  {
   "title": "Top Managed Objects by Alert Mitigation Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 464 },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  managed_object_name AS \"Managed Object\", count(id) AS \"Count\"\nFROM v_alert\nWHERE\n  $__timeFilter(start_time)\n  AND\n  mitigated\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\nGROUP BY 1\nORDER BY 2 desc\n"
    }
   ]
  },
  {
   "title": "Timezone Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 471 },
   "targets": [
    {
     "rawSql": "SELECT\n  name AS \"Timezone Name\", utc_offset AS \"UTC offset\", is_dst as \"Is Daylight saving\"\nFROM pg_timezone_names\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Alert Traffic Rate [F01]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 479 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nSELECT\n  avg(impact_bps) AS \"bps\",\n  avg(impact_pps) AS \"pps\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n"
    }
   ]
  },
  {
   "title": "Max Alert Duration per Security Level [F01]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 488 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH SET1 AS (\nSELECT\n  EXTRACT(epoch FROM max(duration) FILTER (WHERE importance_txt = 'Low' OR NULL)) AS \"Low\",\n  EXTRACT(epoch FROM max(duration) FILTER (WHERE importance_txt = 'Medium' OR NULL)) AS \"Medium\",\n  EXTRACT(epoch FROM max(duration) FILTER (WHERE importance_txt = 'High' OR NULL)) AS \"High\",\n  EXTRACT(epoch FROM max(duration)) as \"Any\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n)\n\nselect \"High\", \"Medium\", \"Low\", \"Any\" from SET1"
    }
   ]
  },
  {
   "title": "TREND: Average Alert Traffic Rate [F02]",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 495 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH vars AS(\nSELECT\n(\n/* var: v_offset */\n(CASE WHEN ($p_offset_selected_duration=true)\n  THEN ($__timeTo()::timestamptz - $__timeFrom()::timestamptz)::interval\n  ELSE interval '0'\n  END)\n  + make_interval(years => $p_offset_years, months => $p_offset_months, weeks => $p_offset_weeks, days => $p_offset_days)) as v_offset\n\n),\nSET1 as (\nSELECT\n  avg(impact_bps) AS \"bps\",\n  avg(impact_pps) AS \"pps\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  \n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n),\nSET2 as (\nSELECT\n  avg(impact_bps) AS \"bps_prev\",\n  avg(impact_pps) AS \"pps_prev\"\nFROM v_alert,vars\nWHERE\n  start_time BETWEEN $__timeFrom()::timestamptz - v_offset\n  AND\n  $__timeTo()::timestamptz - v_offset\n  \n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n)\n\nselect (\"bps\"/NULLIF(\"bps_prev\",0))*100 as \"bps%\", (\"pps\"/NULLIF(\"pps_prev\",0))*100 as \"pps%\", \"bps_prev\", \"pps_prev\" from set1, set2\n"
    }
   ]
  },
  {
   "title": " TREND: Maximum Alert Traffic Rate [F02]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 505 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH vars AS(\nSELECT\n(\n/* var: v_offset */\n(CASE WHEN ($p_offset_selected_duration=true)\n  THEN ($__timeTo()::timestamptz - $__timeFrom()::timestamptz)::interval\n  ELSE interval '0'\n  END)\n  + make_interval(years => $p_offset_years, months => $p_offset_months, weeks => $p_offset_weeks, days => $p_offset_days)) as v_offset\n\n),\nSET1 as (\nSELECT\n  max(impact_bps) AS \"bps\",\n  max(impact_pps) AS \"pps\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n),\nSET2 as (\nSELECT\n  max(impact_bps) AS \"bps_prev\",\n  max(impact_pps) AS \"pps_prev\"\nFROM v_alert, vars\nWHERE\n  start_time BETWEEN $__timeFrom()::timestamptz - v_offset\n  AND\n  $__timeTo()::timestamptz - v_offset\n  \n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n)\n\nselect (\"bps\"/NULLIF(\"bps_prev\",0))*100 as \"bps%\", (\"pps\"/NULLIF(\"pps_prev\",0))*100 as \"pps%\", \"bps_prev\", \"pps_prev\" from set1, set2\n"
    }
   ]
  },
  {
   "title": "Alert Count per Severity Level [F01]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 514 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH alert_count AS (\nSELECT\n  count(importance_txt = 'Low' OR NULL) AS \"Low\",\n  count(importance_txt = 'Medium' OR NULL) AS \"Medium\",\n  count(importance_txt = 'High' OR NULL) AS \"High\",\n  count(id) as \"Total\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n)\n\nselect \"High\", \"Medium\", \"Low\", \"Total\" from alert_count"
    }
   ]
  },
  {
   "title": "TREND: Alert Count per Severity Level [F02]",
   "type": "stat",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 521 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH vars AS(\nSELECT\n(\n/* var: v_offset */\n(CASE WHEN ($p_offset_selected_duration=true)\n  THEN ($__timeTo()::timestamptz - $__timeFrom()::timestamptz)::interval\n  ELSE interval '0'\n  END)\n  + make_interval(years => $p_offset_years, months => $p_offset_months, weeks => $p_offset_weeks, days => $p_offset_days)) as v_offset\n\n),\nalert_count AS (\nSELECT\n  count(importance_txt = 'Low' OR NULL) AS \"Low\",\n  count(importance_txt = 'Medium' OR NULL) AS \"Medium\",\n  count(importance_txt = 'High' OR NULL) AS \"High\",\n  count(id) as \"Total\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n),\nalert_count_prev AS (\nSELECT\n  count(importance_txt = 'Low' OR NULL) AS \"Low_prev\",\n  count(importance_txt = 'Medium' OR NULL) AS \"Medium_prev\",\n  count(importance_txt = 'High' OR NULL) AS \"High_prev\",\n  count(id) as \"Total_prev\"\nFROM v_alert,vars\nWHERE\n  start_time BETWEEN $__timeFrom()::timestamptz - v_offset\n  AND\n  $__timeTo()::timestamptz - v_offset\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n)\n\nselect COALESCE(((\"High\"::float/NULLIF(\"High_prev\",0))*100), 0)::int as \"high%\", COALESCE(((\"Medium\"::float/NULLIF(\"Medium_prev\",0))*100), 0)::int as \"medium%\", COALESCE(((\"Low\"::float/NULLIF(\"Low_prev\",0))*100), 0)::int as \"low%\", COALESCE(((\"Total\"::float/NULLIF(\"Total_prev\",0))*100), 0)::int as \"total%\", \"High_prev\", \"Medium_prev\", \"Low_prev\", \"Total_prev\" from alert_count, alert_count_prev\n"
    }
   ]
  },
  {
   "title": "Average Alert Duration per Security Level [F01]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 532 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SET TimeZone = '$Timezone';\n\nWITH SET1 AS (\nSELECT\n  EXTRACT(epoch FROM avg(duration) FILTER (WHERE importance_txt = 'Low' OR NULL)) AS \"Low\",\n  EXTRACT(epoch FROM avg(duration) FILTER (WHERE importance_txt = 'Medium' OR NULL)) AS \"Medium\",\n  EXTRACT(epoch FROM avg(duration) FILTER (WHERE importance_txt = 'High' OR NULL)) AS \"High\",\n  EXTRACT(epoch FROM avg(duration)) as \"Any\"\nFROM v_alert\nWHERE\n  start_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND\n  /* SharedFilter - START v20220915 */\n  managed_object_name IN ($Managed_Object) AND\n  NOT managed_object_name = Any(ARRAY[$Managed_Object_exclude]::text[]) AND\n  importance_txt IN ($Severity_Level) AND\n  alert_type_txt IN ($Alert_Type) AND\n  direction IN ($Direction) AND\n  impact_bps >= (coalesce(nullif('$min_impact_gbps', ''), '0')::double precision * 1000 * 1000 * 1000) AND\n  INITCAP(mitigated::text) IN ($Mitigated) AND\n  ARRAY[$Mitigation_Type] && mitigation_types AND\n  INITCAP(automitigation::text) IN ($Automitigation)\n  /* SharedFilter - END */\n\n)\n\nselect \"High\", \"Medium\", \"Low\", \"Any\" from SET1"
    }
   ]
  }
 ]
}